### ISSUE TITLE
Add some logging (on by default) when downloading dependencies?

### ISSUE THREAD

**Issue by rainmanhhh** [spring-projects-experimental/spring-boot-thin-launcher#112]
When running thin-jar first time, the console is blocking and there is no message

**Comment by dsyer** [comment]
You can set `thin.debug` or `thin.trace`. I'm not sure I want more output by default. Let me think.

**Comment by dsyer** [comment]
I'm inclined to leave things as they are (i.e. off by default). It's easy to switch logging on and the README tells you how to do it. Anyone else care deeply?
