### ISSUE TITLE
Launching multiple thin jars in single JVM

### ISSUE THREAD

**Issue by nampreetsarao** [spring-projects-experimental/spring-boot-thin-launcher#115]
We are trying to launch multiple thin jars in a single jvm and followed the reference implementation shared by wilkinsona on the following link:
https://github.com/spring-projects/spring-boot/issues/3300

It works fine for fat jars, but for thin-jar it keeps running the first jar over and over again, completely ignoring the next in line jars. Any leads here will be helpful.

**Comment by nampreetsarao** [comment]
We were able to launch multiple thin jars by explicitly stating the --thin.archive and --thin.parent to the jar we were trying to load. Looks like --thin.archive gets sticky with the first jar which gets executed.

**Comment by dsyer** [comment]
Interesting. See also the "deployer" submodule here - it has some utilities for launching multiple jars. We use it in the Spring Cloud CLI, and in Spring Cloud Function.

**Comment by nampreetsarao** [comment]
can you please share the link for the deployer submodule?

**Comment by dsyer** [comment]
Right there in this project (for now anyway): https://github.com/spring-projects-experimental/spring-boot-thin-launcher/tree/master/deployer. Used here: https://github.com/spring-cloud/spring-cloud-cli/tree/master/spring-cloud-launcher (for example).
