### ISSUE TITLE
Multiple repository set, repository with credentials in Gradle

### ISSUE THREAD

**Issue by GergelyLakatos** [spring-projects-experimental/spring-boot-thin-launcher#116]
I really like the idea behind this gradle plugin, however I found the settings thin too.

Actually there is a gradle repo for the co-workers in our company, but this repo is only reachable with credential data. There are stored the common libs. So my gradle file looks like this:

```groovy
repositories {
    mavenCentral()
    maven { url "https://repo.spring.io/snapshot" }
    maven { url "https://repo.spring.io/milestone" }
    maven {
        url "https://...."
        credentials {
            username = "${readerJfrogUser}"
            password = "${readerJfrogUserPw}"
        }
    }
}
```

Its working fine If I build my stuff the original way, however, I can not set multiple repo url, and credentials (for them) in the settings section.

Can it be a future feature? Or has somebody any workaround ?

**Comment by dsyer** [comment]
Not sure what it is exactly that doesn't work. Is it any repository with credentials?

**Comment by GergelyLakatos** [comment]
> Not sure what it is exactly that doesn't work. Is it any repository with credentials?

Yes. We have a Jfrog private repository, what has _username & password_ and an _url_. And I can not set the username and the password (so the credential) in your lib.

So. This app has a property `thin.repo` what accept only a string.

I have a suggestion. `thin.repo` should accept an array, filled with repo objects.
this repo objects, has `url`, `username `and `password ` variable,
e.g.:
`thin.repo = [{url: "..."}, {url: "...", username: "jhon", password: "doe"}]`

My another suggestion that your lib should use the thedault gradle file repo setting.

I hope this comment can clarify my problem / suggestion.

**Comment by dsyer** [comment]
So what are you storing in your JFrog repository (you said "common libs" which I would expect is not `org.springframework*`)? Thing is `thin.repo` is only used to download the thin launcher itself, and the default is to look in Maven Central. If you have an internet connection it should work.

What are you trying to do and what it is that isn't working? What is the expected outcome, and what is the actual outcome? Are you providing a `settings.xml` with your JFrog repository credentials configured?

**Comment by GergelyLakatos** [comment]
Thanks for the response.

I would like to optimize my cicd pipeline. I would like to made a thin.jar what contains only the code what I wrote, and a common.jar what contains the dependencies. (In this way, most of the time, the jenkins should compile only the thin.jar)
I could make a thin jar, but I can not made a common.jar with this gradle-module, beacuse the error msg said, that my specific common libs (what i store our private repo) is not available. But I can not set our repo url, because it needs the credentials

**Comment by dsyer** [comment]
You need to install the common jar in the local .m2 cache, or provide the credentials (e.g. in settings.xml) as suggested. Either would work.

**Comment by GergelyLakatos** [comment]
Thanks the suggestion, but thats not good for me, because I build a docker image like this:

```
FROM openjdk:11-jre-slim AS base
...
FROM gradle:5.5.1-jdk11 AS build
....
```
So with your solution I have to build _my own gradle docker build_ image every time when the common.jar changes.. and it increases the complexity more, that I would win with this.

But anyway thanks for your answers!

**Comment by dsyer** [comment]
I don't understand. If you have a common jar and it is available to download with Gradle, why can you not keep it in the local cache? I'm sure you can. If you do it and show us how it works, then we can see if it is complex or not, and if it justifies the additional complexity in the tooling. Can you do that?

**Comment by GergelyLakatos** [comment]
Okey, let me explain. We dont have this cache option, because our build system is not an usual one.

Dockerfile looks like this:
```
FROM openjdk:11-jre-slim AS base
WORKDIR /app


FROM gradle:5.5.1-jdk11 AS build
COPY . /src
WORKDIR /src
RUN ["gradle", "clean", "build", "-PexcludeRepoTests"]


FROM base AS final
COPY --from=build /src/build/libs/myapp* /app/myapp.jar
ENTRYPOINT ["java", "-jar", "/app/myapp.jar"]
```

So we have no gradle cache in the jenkins  (build) server, because we use a docker image for build (gradle:5.5.1-jdk11), and an another one for run it (openjdk:11-jre-slim).
Our jenkins is abstract, and it handles nothing but docker build, and deploy.

So (with your solution), I have to make an _automation_, for making a _builder docker image_ what would contain all the dependencies what it need for the build, and it should be changed as the deps changes.. Its complicated.

My goal was a Dockerfile like this:
```
FROM openjdk:11-jre-slim AS base
WORKDIR /app


FROM gradle:5.5.1-jdk11 AS build
COPY . /src
WORKDIR /src
RUN ["gradle", "clean", "buildonlydependencies"] # it makes the jar of dependencies
RUN ["gradle", "clean", "buildcore", "-PexcludeRepoTests"] # it makes the core jar and runs the tests


FROM base AS final
COPY --from=build /src/build/libs/myapp* /app/myapp.jar
ENTRYPOINT ["java", "-jar", "/app/myapp.jar"]
```
And why is it good for me? Because if a gradle command like _buildonlydependencies_ would exist, the docker would handle it so well, because it can make a cache layer from it, so that step would come from the docker cache (if the deps does not change), and most of the time the build process should focus only the core.jar.

I hope you can understand now.

**Comment by dsyer** [comment]
We seem to have veered off topic from the original issue though, or am I missing something? The original topic was about custom repositories with credentials. It wasn't anything to do with multistage docker builds and optimization of docker caches.

All you need to make it work is a Maven `settings.xml` with the repository credentials. You have to figure out a way to inject the secrets from environment variables, but I know it's possible (plenty of docs if you google), and you already have that problem with the `build.gradle`, so you must have solved it somehow.
