### ISSUE TITLE
Logging is turned off by default when application uses java.util.logging

### ISSUE THREAD

**Issue by psefranek** [spring-projects-experimental/spring-boot-thin-launcher#118]
As can be seen in class `org.springframework.boot.loader.thin.ThinJarLauncher`, logging is turned off several times (by calling `LogUtils.setLogLevel(Level.OFF)`). However it seems that logging is never turned back on. If launched application uses standard `java.util.logging.Logger` all messages are discarded. 

As a workaround one can run jar with system property `-Dthin.debug=true` which restores logging level to default INFO (line 172 in class `ThinJarLauncher`). However I think that log level should be restored to standard Java's default (INFO) regardless of whether debug system property was used or not.

Thanks for your time and keep up the good work!
Pavel

**Comment by dsyer** [comment]
The thin launcher uses a different class loader to the app, so it's surprising if it pollutes the loggers in the app code. I thought at first it was because you are using `java.util.logging`, but I tried an app with `slf4j-jdk14` and it seems to work fine. Do you have an example that doesn't log anything? Can you post a simple sample to github?

> Thanks for your time and keep up the good work!

You are more than welcome. Keep on sending feedback.

**Comment by psefranek** [comment]
Hi Dave, thanks for reply. I have created a minimal working example.

`pom.xml`:
```xml
<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>test</groupId>
	<artifactId>test-logger</artifactId>
	<version>1.0-SNAPSHOT</version>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<maven.compiler.source>1.8</maven.compiler.source>
		<maven.compiler.target>1.8</maven.compiler.target>
	</properties>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
				<version>2.2.0.RELEASE</version>
				<dependencies>
					<dependency>
						<groupId>org.springframework.boot.experimental</groupId>
						<artifactId>spring-boot-thin-layout</artifactId>
						<version>1.0.22.RELEASE</version>
					</dependency>
				</dependencies>
				<executions>
					<execution>
						<goals>
							<goal>repackage</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>
</project>
```

`App.java`:
```java
package test;

import java.util.logging.Level;
import java.util.logging.Logger;

public class App {

	private static final Logger log = Logger.getLogger(App.class.getName());

	public static void main(String[] args) throws InterruptedException {
		while (true) {
			log.log(Level.INFO, "Hello world!");
			Thread.sleep(1_000);
		}
	}
}
```

Now create executable JAR using `mvn package`, then start packaged JAR (`java -jar target/test-logger-1.0-SNAPSHOT.jar`). When you start JAR without switch `-Dthin.debug=true` nothing is logged to the console.

**Comment by dsyer** [comment]
Hmm. My tests were using a `@SpringBootApplication`. I think Spring Boot resets the `Logger` for you if you do that. But your app should work now too.
