### ISSUE TITLE
thinResolve Task as Part of the Gradle Script

### ISSUE THREAD

**Issue by SudharakaP** [spring-projects-experimental/spring-boot-thin-launcher#122]
I am working on [integrating spring-boot-thin-launcher with JHipster](https://github.com/jhipster/generator-jhipster/pull/10420) and I could integrate the maven plugin so that when the relevant build profile is triggered the dependencies are resolved to the correct directory using something similar to; 

```xml
<plugin>
	<groupId>org.springframework.boot.experimental</groupId>
	<artifactId>spring-boot-thin-maven-plugin</artifactId>
	<version>1.0.23.RELEASE</version>
	<configuration>
		<outputDirectory>${project.build.directory}/appengine-staging</outputDirectory>
	</configuration>
	<executions>
		<execution>
			<id>resolve</id>
			<goals>
				<goal>resolve</goal>
			</goals>
			<inherited>false</inherited>
		</execution>
	</executions>
</plugin>
```

However I was unable to find a task to achieve a similar thing in the Gradle plugin; which results in two commands firstly to execute `./gradlew thinResolve` and then whatever commands afterwards to deploy it. 

Is there any other more elegant way to do this on the Gradle side which the Gradle thin plugin supports? 😄

**Comment by dsyer** [comment]
I guess you can do anything with Gradle? You can define your own task that calls `thinResolve` and then the other thing (whatever that was), or make `thinResolve` a dependency of the other thing. That's the way Gradle works isn't it?

**Comment by SudharakaP** [comment]
@dsyer : Thanks much; your answer helped me to figure it out. Yes, all I got to do was to add thinResolve as a dependency. I am still new to Gradle. 😄
