### ISSUE TITLE
hot replace jar file in repository do not work

### ISSUE THREAD

**Issue by einsteinarbert** [spring-projects-experimental/spring-boot-thin-launcher#123]
When I replace some jar by new jar file, it was shown error below:

```
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.wrapper.ThinJarWrapper.launch(ThinJarWrapper.java:140)
        at org.springframework.boot.loader.wrapper.ThinJarWrapper.main(ThinJarWrapper.java:107)
Caused by: java.lang.RuntimeException: Could not find artifact com.lowagie:itext:jar:2.1.7.js6 in spring-snapshots (https://repo.spring.io/libs-snapshot)
Could not find artifact com.lowagie:itext:jar:2.1.7.js6 in central (https://repo1.maven.org/maven2)
Could not find artifact com.lowagie:itext:jar:2.1.7.js6 in spring-milestones (https://repo.spring.io/milestone)
Could not find artifact com.lowagie:itext:jar:2.1.7.js6 in archiva.internal 
```

Therefore, I must to be rebuilded all it again.
So, I don't why it can't replace entry one jar file by another same source code, there are only difference between them is I rebuilded the new one file and replace to old file, no change in source code.

**Comment by dsyer** [comment]
Sorry, it's not clear what you did. What do you mean "replace some jar by new jar file"? If you have a sample project with steps to reproduce it might be possible to see what happened. It looks like maybe you are trying to resolve a non-existent dependency (`com.lowagie:itext:jar:2.1.7.js6`)?

**Comment by einsteinarbert** [comment]
It's mean I changed tiny code in my class and using: "mvn clean install
package" to rebuild it and replace that jar file into depedency folder, but
the spring boot cannot lauched again.

Vào 19:10, T.6, 13 Th12, 2019 Dave Syer <notifications@github.com> đã viết:

**Comment by dsyer** [comment]
What "tiny code" did you change? Without steps to reproduce I'm guessing. Did you change one of the dependencies? Did you expect `com.lowagie:itext:jar:2.1.7.js6` to exist somewhere (it isn't in Maven Central)?

**Comment by einsteinarbert** [comment]
no, for example, I just edit a class, add if else clause and rebuild my
jar, replace it into .m2/repository and run spring thin laucher but it got
error. Not the error of dependencies, I think my check sum file of jar is
wrong so the spring thin laucher cannot recognize my new jar file. It
happens sometime and I'm sorry I don't have screen shoot of log, I will
update early.

Vào 22:37, T.6, 13 Th12, 2019 Dave Syer <notifications@github.com> đã viết:

**Comment by dsyer** [comment]
Please try to create a stable way to reproduce the problem. Screenshots are hardly ever helpful. A complete description of what you did and a full stack trace might be helpful though.

**Comment by einsteinarbert** [comment]
Hey, here is my stack trace, I just restart server by re-run command:
 nohup java -Duser.timezone=Asia/Ho_Chi_Minh -Dthin.root=/opt/xxx
-Dthin.location=./config/ -jar xxx-api-0.0.1-SNAPSHOT.jar
--spring.profiles.active=vpn &
It show error same as I describled above.

Vào Th 7, 14 thg 12, 2019 vào lúc 00:11 Dave Syer <
notifications@github.com> đã viết:

**Comment by einsteinarbert** [comment]
I think when the first time I run server, everything ok but spring deleted or change something and I cannot run in second time, this error sometime happend, somethime not happend, therefore I don't known what is real reason :(

**Comment by dsyer** [comment]
Ok, well “spring” never deletes or changes anything in your file system, as far as I know. If you can narrow it down a bit and provide some pointers to help you, maybe that would be a good idea? There isn’t much to go on right now, but if you want help, you only have to ask the right way. I really hope you can do that.

**Comment by einsteinarbert** [comment]
okey, I will reproduce this bug and debug it, take long time to do...

Vào 05:06, T.7, 14 Th12, 2019 Dave Syer <notifications@github.com> đã viết:

**Comment by dsyer** [comment]
I'm not sure this is going anywhere. If there's more information please come back.
