### ISSUE TITLE
cannot resolve jar with spring-boot-thin-maven-plugin

### ISSUE THREAD

**Issue by rivenhk** [spring-projects-experimental/spring-boot-thin-launcher#124]
```
<dependencyManagement>
 <dependencies>
  <dependency>
    <groupId>com.google.cloud</groupId>
    <artifactId>libraries-bom</artifactId>
    <version>2.8.0</version>
    <type>pom</type>
    <scope>import</scope>
   </dependency>
 </dependencies>
</dependencyManagement>

<dependency>
  <groupId>com.google.cloud</groupId>
  <artifactId>google-cloud-storage</artifactId>
</dependency>
```

I have a dependency of google cloud storage in the parent pom, when i try to package jar of sub module, some google cloud jars are missing, but if i add the dependency directly in the child pom, the jars can be resolved correctly and pack in the repository. Any idea why it is not working with parent pom?

**Comment by dsyer** [comment]
No idea, sorry. If you can prepare a simple, minimal sample that shows the issue we can probably get to the bottom of it.

**Comment by dsyer** [comment]
Works for me with a simple web app. We'd need a sample to investigate (can re-open if someone can provide one).
