### ISSUE TITLE
Exception in thread "main" java.lang.ClassNotFoundException: org.springframework.boot.loader.thin.ThinJarLauncher

### ISSUE THREAD

**Issue by kymowang** [spring-projects-experimental/spring-boot-thin-launcher#126]
I make a new simple springboot project and package using spring-boot-thin-launcher, but get error . The project only contains one simple DemoApplication class.
plugins tag in pom.xml:

> <build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
				<dependencies>
					<dependency>
						<groupId>org.springframework.boot.experimental</groupId>
						<artifactId>spring-boot-thin-layout</artifactId>
						<version>1.0.23.RELEASE</version>
					</dependency>
				</dependencies>
			</plugin>
			<plugin>
				<groupId>org.springframework.boot.experimental</groupId>
				<artifactId>spring-boot-thin-maven-plugin</artifactId>
				<version>1.0.23.RELEASE</version>
				<executions>
					<execution>
						<id>resolve</id>
						<goals>
							<goal>resolve</goal>
						</goals>
						<inherited>false</inherited>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>

error message when running mvn package:
```
[INFO] --- spring-boot-thin-maven-plugin:1.0.23.RELEASE:resolve (resolve) @ demo ---
[INFO] Deploying: D:\github\test\target\demo-0.0.1-SNAPSHOT.jar
[INFO] Copying: demo-0.0.1-SNAPSHOT.jar to D:\github\test\target\thin\root
Picked up JAVA_TOOL_OPTIONS: -Duser.language=en
Exception in thread "main" java.lang.ClassNotFoundException: org.springframework.boot.loader.thin.ThinJarLauncher
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at org.springframework.boot.loader.wrapper.ThinJarWrapper.launch(ThinJarWrapper.java:139)
        at org.springframework.boot.loader.wrapper.ThinJarWrapper.main(ThinJarWrapper.java:107)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 8.095s
[INFO] Finished at: Mon Dec 30 20:27:36 CST 2019
[INFO] Final Memory: 26M/446M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.springframework.boot.experimental:spring-boot-thin-maven-plugin:1.0.23.RELEASE:resolve (resolve) on project demo: Cannot locate deployable D:\github\test\target\demo-0.0.1-SNAPSHOT.jar: Could not exec java: Application fini
shed with exit code: 1 -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```
Any help is appreciated!

**Comment by dsyer** [comment]
Could be a bad jar file? Maybe delete the thin launcher jar from your Maven cache?

**Comment by kymowang** [comment]
Not work for me. I debug the maven plugin. Error occurs in org.springframework.boot.experimental.maven.ThinJarMojo.java line 117
```
RunProcess runProcess = new RunProcess(workingDirectory,
					cmd.toArray(new String[0]));
			Runtime.getRuntime()
					.addShutdownHook(new Thread(new RunProcessKiller(runProcess)));
			getLog().debug("Running: " + archive);
			int exitCode = runProcess.run(true, args);
			if (exitCode == 0 || exitCode == EXIT_CODE_SIGINT) {
				return;
			}
```
The existCode is 1. Argument `workingDirectory` is target/thin/root and `cmd` is `C:\Program Files\Java\jdk1.8.0_111\jre\bin\java.exe -Dthin.repo=http://maven.aliyun.com/nexus/content/groups/public -Dmaven.repo.local=D:\maven\repo -Dthin.dryrun -Dthin.root=. -jar D:\github\test\target\demo-0.0.1-SNAPSHOT.jar`
It outputs
```
Exception in thread "main" java.lang.ClassNotFoundException: org.springframework.boot.loader.thin.ThinJarLauncher
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at org.springframework.boot.loader.wrapper.ThinJarWrapper.launch(ThinJarWrapper.java:139)
        at org.springframework.boot.loader.wrapper.ThinJarWrapper.main(ThinJarWrapper.java:107)
```
I dont know how to continue to resolve the issue.

**Comment by kymowang** [comment]
Well, I changed maven repository and succeeded.
