### ISSUE TITLE
How can I load the jar package inside the thin jar

### ISSUE THREAD

**Issue by xtaetg** [spring-projects-experimental/spring-boot-thin-launcher#127]
If I put the jars generated by the submodules into a thin jar (third-party jars are still placed outside), how can I load the jars generated by these submodules when starting the thin jar

**Comment by dsyer** [comment]
You just need them to be in a maven repository. Can be the local cache. What did you try that didn't work? There's a sample in this project that works for instance.

**Comment by dsyer** [comment]
Possible duplicate of #15?

**Comment by xtaetg** [comment]
I dont't want to put them in my maven repository. When I upgrade my programe,I just need to provide only one jar to my customer, otherwise I need to provider more jars and a script to put them into the maven local cache. thanks.

**Comment by dsyer** [comment]
Definitely a duplicate then, but the context is useful, thanks.
