### ISSUE TITLE
thin.force resolved to a blank string when thin.force and thin.dryRun both unspecified

### ISSUE THREAD

**Issue by AminLA** [spring-projects-experimental/spring-boot-thin-launcher#131]
@org.springframework.boot.loader.thin.ThinJarLauncher.getResolver()
```java
String force = environment.resolvePlaceholders(
        "${" + THIN_FORCE + ":${" + THIN_DRYRUN + ":false}}");
...
if (!"false".equals(force)) {
    resolver.setForce(true);
}
```

change to Boolean.parseBoolean solves the problem
```java
if (Boolean.parseBoolean(force)) {
    resolver.setForce(true);
}
```

**Comment by dsyer** [comment]
I'm not quite sure what you are getting at. When `THIN_FORCE` and `THIN_DRYRUN` are null then `force` (in the code above) is "false", right? We don't want to use `Boolean.parseBoolean()` because we want "empty but unset" to be "true". So what was the exact scenario that you didn't like the result for, and why?

**Comment by AminLA** [comment]
i was running cmd 
```
mvn -Dmaven.repo.local=M:\_mvnRepo package spring-boot-thin:resolve -offline
```
and expecting it resolves dependencies from precomputed thin.properties
but it always resolve dependencies from pom, 
so i print out force variable, and it turns out that it's not "false" but an empty string

it seems that org.springframework.boot.experimental.maven.ThinJarMojo.runWithForkedJvm(File, File, String...) specified the thin.dryRun cause this

```java
List<String> cmd = new ArrayList<>(
        Arrays.asList(new JavaExecutable().toString(), "-Dthin.dryrun",
                "-Dthin.root=.", "-jar", archive.getAbsolutePath()));
```

**Comment by dsyer** [comment]
I see. I don't think we ever had that use case in mind. Did you expect `-offline` to somehow translate to `thin.force=false` (because as you can see from the code, when `thin.dryrun` is set then so is `thin.force` by default)? I'm not sure that makes sense for everyone, but we could probably add a flag that allows you to set `thin.force=false` explicitly.

**Comment by AminLA** [comment]
1. i didn't expected mvn flag `-offline` to translate to thin flag `thin.forece=false`, i use that flag only to prevent remote network connection
2. i can tell that resolve mojo fork process and launching ThinJarLauncher, and hence it's a dryrun
but why `thin.force` is correlated to `thin.dryrun`

**Comment by dsyer** [comment]
It seems like a decent default to me - if you asked for a dry run, then you probably want to compute the dependencies. It’s only a default (but as I said if you need something in the maven plug-in that allows you to override then that’s probably not hard).

**Comment by AminLA** [comment]
ok, i know where the problem is

i bind properties mojo to prepare-package phase, 
so after prepare-package phase the dependencies is computed
and i think it should not resolve it again in resolve mojo (package phase)
but, this is not the use case that you expected, 
because pre generate thin.properties is not mandatory

thinks for the clarification :)

```xml
<!-- generate META-INF/thin.properties -->
<plugin>
    <groupId>org.springframework.boot.experimental</groupId>
    <artifactId>spring-boot-thin-maven-plugin</artifactId>
    <version>${thin.launcher.version}</version>
    <executions>
        <execution>
            <id>generate-thin-properties</id>
            <phase>prepare-package</phase>
            <goals>
                <goal>properties</goal>
            </goals>
        </execution>
    </executions>
</plugin>
```
