### ISSUE TITLE
is documentation actual?

### ISSUE THREAD

**Issue by sorin-costea** [spring-projects-experimental/spring-boot-thin-launcher#133]
If I try as described right here:
```
<plugin>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-maven-plugin</artifactId>
	<version>2.2.5.RELEASE</version>
	<dependencies>
		<dependency>
			<groupId>org.springframework.boot.experimental</groupId>
			<artifactId>spring-boot-thin-layout</artifactId>
			<version>1.0.24.RELEASE</version>
		</dependency>
	</dependencies>
</plugin>
```
Then nothing happens - I get a tiny JAR with my own classes but no wrapper and no manifest.
I notice in another issue here somebody else using "as documented" but I cannot find his documented way in the documentation, and trying it doesn't work either:
```
<plugin>
				<groupId>org.springframework.boot.experimental</groupId>
				<artifactId>spring-boot-thin-maven-plugin</artifactId>
				<version>1.0.23.RELEASE</version>
				<executions>
					<execution>
						<id>resolve</id>
						<goals>
							<goal>resolve</goal>
						</goals>
						<inherited>false</inherited>
					</execution>
				</executions>
			</plugin>
```
because the thin plugin fails when copying the JAR with "no main manifest attribute".
So... how should I use the plugin? I checked also the examples from https://github.com/spring-cloud but they are using the above solution which for me doesn't produce anything...

**Comment by dsyer** [comment]
Your first snippet looks right to me (and is consistent with both the README and all the samples). Can you share the an example project that doesn't work, please?

**Comment by sorin-costea** [comment]
I'm sorry I cannot, I gave up Spring Boot thin launcher and switched to Quarkus...
