### ISSUE TITLE
Deploying to Cloud Foundry error

### ISSUE THREAD

**Issue by alan-denight** [spring-projects-experimental/spring-boot-thin-launcher#135]
when follow the instructions on Deploying to Cloud Foundry section, we encounter the below errors:

```
[Buildpack]                      ERROR Finalize failed with exception #<RuntimeError: No container can run this application. Please ensure that you've pushed a valid JVM artifact or artifacts using the -p command line argument or path manifest entry. Information about valid JVM artifacts can be found at https://github.com/cloudfoundry/java-buildpack#additional-documentation. >
   No container can run this application. Please ensure that you've pushed a valid JVM artifact or artifacts using the -p command line argument or path manifest entry. Information about valid JVM artifacts can be found at https://github.com/cloudfoundry/java-buildpack#additional-documentation.
Failed to compile droplet: Failed to run finalize script: exit status 1
```

 we are using the    <version>1.0.24.RELEASE</version>

```
	<plugin>
            <groupId>org.springframework.boot.experimental</groupId>
            <artifactId>spring-boot-maven-plugin</artifactId>
            <version>1.0.24.RELEASE</version>
            <dependencies>
                <dependency>
                    <groupId>org.springframework.boot.experimental</groupId>
                    <artifactId>spring-boot-thin-launcher</artifactId>
                    <version>1.0.24.RELEASE</version>
                </dependency>
            </dependencies>
        </plugin>
```

**Comment by dsyer** [comment]
`1.0.24.RELEASE` is not a valid version for the `spring-boot-maven-plugin`. Are you sure about that?

**Comment by alan-denight** [comment]
Hi Dsyer,

Version 1.0.24.RELEASE is in Maven Central, snapshots are in https://repo.spring.io/libs-snapshot. See https://github.com/spring-projects/spring-boot/issues/1813 for more discussion and ideas(https://github.com/spring-projects-experimental/spring-boot-thin-launcher)

if it is not the Version 1.0.24.RELEASE, which version should we sue? Thanks!

**Comment by dsyer** [comment]
1.0.24.RELEASE is a valid version number for the thin launcher, not the Spring Boot Maven plugin. There's no way the pom.xml looks like your snippet above, if it works and produces a valid jar file, so I assume it's a typo? Can you run your jar file locally (i.e. not in CF)?

**Comment by alan-denight** [comment]
Hi Dsyer,
is there a sample project for reference regarding the configuration of Spring Boot Maven plugin and spring-boot-thin-launcher?

**Comment by dsyer** [comment]
There are examples in the README, and about 10 sample projects in the project in Github (see under "samples").

**Comment by dsyer** [comment]
Assume user error with plugin configuration. Please shout if you have more information.
