### ISSUE TITLE
How to use the plugin in project with multiple maven modules?

### ISSUE THREAD

**Issue by YiuTerran** [spring-projects-experimental/spring-boot-thin-launcher#137]
Hello, my project layout like this:

```
├── pom.xml
├── app1
│   ├── pom.xml
│   ├── src
├── app2
│   ├── pom.xml
│   ├── src
├── lib1
│   ├── pom.xml
│   ├── src
├── lib2
│   ├── pom.xml
│   ├── src
```

Now, if i put the plugin in `app1/pom.xml` within `<build>` tag, and then run `mvn package`. 

After running the built jar of app1, it will echo `Non-resolvable parent POM` . 

Of course, the parent pom can't be found at `repo.spring.io`, since i can't publish this project.

Any advice please? Thanks a lot.

**Comment by dsyer** [comment]
This looks a bit like the "multi" sample. What's different (not enough information in your description to tell really)? Do you have an example that you can link to?

**Comment by dsyer** [comment]
You would probably need at least to `mvn install` everything (you only said you did a `mvn package` which isn't enough to put all the artifacts in your local cache). Did that help?

**Comment by YiuTerran** [comment]
So, in this case, i have to publish the `lib1` and `lib2` to a private nexus repo, if i want to use the thin plugin without making the libs public.

Am i right?

**Comment by dsyer** [comment]
Not strictly true. You only need a local cache with the libraries, not a full private repo. If you `mvn install` them it will work, right?

**Comment by YiuTerran** [comment]
Yes, with `mvn install` the jar can be ran at localhost. 

But if i want to deploy the jar in server within docker, i have to publish the libs to a private repo.

**Comment by dsyer** [comment]
Wouldn’t it be better to ship the container with its dependencies?

**Comment by jameshugit** [comment]
The way I deal with this issue is:
1) pack all the sub-module jars to thin jar "lib" directory and add thin.properties (removed sub-module jars)
2) custom spring-boot-thin-launcher to resolve dependencies from thin.properties only and then load jars from "lib"

It works, but finally I found the performance is bad, double time cost to run the app.

**Comment by huyangcheng** [comment]
> The way I deal with this issue is:
> 
> 1. pack all the sub-module jars to thin jar "lib" directory and add thin.properties (removed sub-module jars)
> 2. custom spring-boot-thin-launcher to resolve dependencies from thin.properties only and then load jars from "lib"
> 
> It works, but finally I found the performance is bad, double time cost to run the app.

How is it set up？

**Comment by ssyangchn** [comment]
Yes, not friendly enough for multi-module projects, so I gave up using this plugin

**Comment by dsyer** [comment]
I don’t really understand what the problem is. All you need is a local cache (which is the default for Maven).

**Comment by ssyangchn** [comment]
> I don’t really understand what the problem is. All you need is a local cache (which is the default for Maven).

maven install can be installed locally and run locally, but when I transfer the jar file to the server to run, there is no cache on the server. And obviously, the dependencies of those project modules cannot be downloaded from the repository because they are not uploaded to the public maven repository

**Comment by dsyer** [comment]
Ah, I see. So you aren’t using a container? But then how would it work? You’d have to transfer all your local jar files to the server. That would work already if you put them in a subdirectory with the right name (following the maven repo conventions). There might even be a way to do it with `mvn deploy`.

**Comment by ssyangchn** [comment]
> Ah, I see. So you aren’t using a container? But then how would it work? You’d have to transfer all your local jar files to the server. That would work already if you put them in a subdirectory with the right name (following the maven repo conventions). There might even be a way to do it with `mvn deploy`.

Using `mvn deploy` means I need to run a maven private repo, which obviously increases the workload.
Currently I use `spring-boot-maven-plugin` to package all dependencies into a FatJar to run

**Comment by dsyer** [comment]
> Using mvn deploy means I need to run a maven private repo, which obviously increases the workload.

I’m not sure that’s 100% the only solution. Maven can deploy to a filesystem for instance. So probably it could deploy to your server directly with only ssh or ftp access (or something).
