### ISSUE TITLE
Execution resolve of goal org.springframework.boot.experimental:spring-boot-thin-maven-plugin:1.0.24.RELEASE:resolve failed.

### ISSUE THREAD

**Issue by yang771036958** [spring-projects-experimental/spring-boot-thin-launcher#141]
Execution resolve of goal org.springframework.boot.experimental:spring-boot-thin-maven-plugin:1.0.24.RELEASE:resolve failed.

**Comment by yang771036958** [comment]
please~

**Comment by dsyer** [comment]
Not much information to go on there. Is there a stack trace? Error message? Did you get some DEBUG logs?

**Comment by dsyer** [comment]
Works for me. Maybe try the latest version?
