### ISSUE TITLE
Custom logging message on start up

### ISSUE THREAD

**Issue by Tudor44** [spring-projects-experimental/spring-boot-thin-launcher#142]
Linking this issue to #118, Is there a way to add a custom message during the start-up of the project?

**Comment by dsyer** [comment]
What do you mean by "during startup"? What kind of message would it be?

**Comment by Tudor44** [comment]
> What do you mean by "during startup"? What kind of message would it be?

During the download of dependencies on before the run of Spring boot application, is it possible to log at that instant some Infos?

**Comment by dsyer** [comment]
What info do you have that isn't already logged? If you have a custom launcher you can add anything you want of course. I need an example.

**Comment by Tudor44** [comment]
> What info do you have that isn't already logged? If you have a custom launcher you can add anything you want of course. I need an example.

Log metrics like:

Brief examples.
1) the start/end date of downloading
2)Numbers of jars downloaded
3) with what status? 

Stuff like this. 

Thanks.

**Comment by dsyer** [comment]
OK. That's a start. I think you can derive all of that from the logs you have, but you would like a summary. Do you want to be able to plug some code in somewhere, so you can log this stuff yourself (is that what you mean by "custom")?

BTW, I'm not sure there is such a thing as a "status" for a jar - if something failed to download you will see an exception.

**Comment by Tudor44** [comment]
> OK. That's a start. I think you can derive all of that from the logs you have, but you would like a summary. Do you want to be able to plug some code in somewhere, so you can log this stuff yourself (is that what you mean by "custom")?
> 
> BTW, I'm not sure there is such a thing as a "status" for a jar - if something failed to download you will see an exception.

Yes, adding a sort of report which contains some information (better pluggable) regards the deploy of spring boot, prior to the effective starting of app with all dependencies.

**Comment by dsyer** [comment]
I added a summary of the time taken to resolve dependencies. I don't have any great ideas for extension points other than writing your own subclass of `ThinJarLauncher`. The other information you asked for (number of jars resolved) is available from existing logs. AFAIK there is no way to know where a jar file was resolved from.

**Comment by Tudor44** [comment]
Thank you so much. For the other requests, I will try to play around using the`ThinJarLauncher ` class
