### ISSUE TITLE
Can't override localRepository from settings.xml using thin.root

### ISSUE THREAD

**Issue by jg-try** [spring-projects-experimental/spring-boot-thin-launcher#145]
Issue with a project built as a thin jar (with its dependencies downloaded under /thin/root/repository) and run with 'java -jar -Dthin.root=/thin/root *.jar'.

The issue comes when the settings.xml of the .m2 has a value in <localRepository> (like '/home/jgt/.m2/repository'). This parameter has priority over the declaration of the repo '/thin/root', so the project does not use anymore the dependencies under '/thin/root'.

**Comment by dsyer** [comment]
There's a test that supposedly disproves this. What version of the thin launcher were you using?

**Comment by dsyer** [comment]
No feedback. Maybe not an issue any more?
