### ISSUE TITLE
Ability to read from ~/.m2 but save into the given thin.root for faster builds

### ISSUE THREAD

**Issue by holyjak** [spring-projects-experimental/spring-boot-thin-launcher#147]
I need something that I would expect to be a very common use case: I want to output all the dependencies of my thin jar into a directory without downloading them all anew when they already are in my local maven repository. Currently this seems impossible (without running Nexus or something similar).

What I do on my build server is:

```
gradle build # fetches build and runtime dependencies, produces a thin jar
java -Dthin.root=./libs-root -jar myapp-thin.jar
package-into-docker ./libs-root myapp-thin.jar
``` 

Am I missing something? Thank you!!!

**Comment by dsyer** [comment]
I'm pretty sure it works for me, but maybe only for Maven. If you set `thin.root` then the local `~/.m2` is added to the repositories,

**Comment by holyjak** [comment]
Yes, but the local ~/.m2 contains bunch of crap from build/dev-time dependencies and other projects, not something I want included in the uberjar.

**Comment by dsyer** [comment]
I'm not sure we are talking about the same problem then. If you set `thin.root` you expect to only see only the app dependencies right?

Also FYI, it can be quite useful to run `java -jar ...` with `thin.classpath` (not `thin.root`) if you only want to download and locate the dependencies, and then run with `java -cp ...` in your container.

**Comment by holyjak** [comment]
Correct.

In itself, thin.root works and I get only the app runtime dependencies in a directory ready to be included in my Docker image. As mentioned, I cannot use the default `~/.m2` because this will include additional, build-time and testing dependencies. The problem I have with a custom thin.root is this: it will, on every build, re-download all the dependencies from scratch. We could cache them (I assume) but then there is no way to get rid of dependencies that have changed (unless we do some extra logic).

What I desire is:
* Be able to get only the app's runtime dependencies in a directory - for that I believe I need to set custom thin.root
* Be able to cache the dependencies (on my CI server) so that they don't need to be re-downloaded from the Maven Central
* Have dependencies that are not used anymore purged so that they don't stay in the cache forever (in the worst case I could just manually purge the cache every month...).

**Comment by dsyer** [comment]
> for that I believe I need to set custom `thin.root`

Not exactly. There is the `thin.classpath` approach as well.

Irrespective of that, I was pretty sure this worked as you described anyway. I'll see what happens locally for me.

Question: what version of the thin launcher are you using (it might make a difference)?

**Comment by holyjak** [comment]
1.0.24.RELEASE

**Comment by dsyer** [comment]
You definitely should try 1.0.25 at least. And snapshots of that doesn’t work.

**Comment by dsyer** [comment]
Using the "simple" sample from this repo (disconnected from network):

```
$ java -jar target/simple-0.0.1-SNAPSHOT.jar --thin.dryrun --thin.root=target/thin
$ find target/thin/ -name \*.jar
target/thin/repository/ch/qos/logback/logback-core/1.2.3/logback-core-1.2.3.jar
target/thin/repository/ch/qos/logback/logback-classic/1.2.3/logback-classic-1.2.3.jar
...
```

So I think it works.

**Comment by holyjak** [comment]
According to https://plugins.gradle.org/plugin/org.springframework.boot.experimental.thin-launcher the latest available release is 1.0.24.RELEASE :-(

How do I use a plugin version that has not been released?

**Comment by dsyer** [comment]
Sigh. It's in the Maven Central (https://repo1.maven.org/maven2/org/springframework/boot/experimental/spring-boot-thin-gradle-plugin/1.0.25.RELEASE/) so you can get it from there. I'll have to look into why Gradle Central, or whatever they call it, is not picking up the latest releases. If anyone has a clue how to debug that it would be good to hear from them.

**Comment by holyjak** [comment]
I guess I do something wrong, it only gathers POMs, not JARs: 

```
$ java -Dthin.root=repo -Dthin.dryrun=true -Dthin.debug=true -Dthin.trace=true -jar ./build/libs/minbedrift.jar                         Using launcher: repo/repository/org/springframework/boot/experimental/spring-boot-thin-launcher/1.0.25.RELEASE/spring-boot-thin-launcher-1.0.25.RELEASE-exec.jar
...
Oct 02, 2020 4:14:01 PM org.springframework.boot.loader.thin.DependencyResolver dependencies
INFO: Computing dependencies from pom and properties




Oct 02, 2020 4:17:13 PM org.springframework.boot.loader.thin.ThinJarLauncher getClassPathArchives
INFO: Dependencies resolved in: 193905ms
Oct 02, 2020 4:17:13 PM org.springframework.boot.loader.thin.ThinJarLauncher launch
INFO: Downloaded dependencies to repo

$ du -h -d 0 repo
 21M	repo # expected ± 100MB

$ find repo/ -name \*.jar
repo//repository/org/springframework/boot/experimental/spring-boot-thin-launcher/1.0.25.RELEASE/spring-boot-thin-launcher-1.0.25.RELEASE-exec.jar
repo//repository/org/springframework/boot/experimental/spring-boot-thin-launcher/1.0.24.RELEASE/spring-boot-thin-launcher-1.0.24.RELEASE-exec.jar
```

**Comment by dsyer** [comment]
There are some issues with the Gradle plugin at the moment, so my guess is you are seeing that. It only works with some versions of Gradle.

I guess you could try Maven to make sure it works for you, or look at the versions of Gradle in the samples, and pick one of those.

Can you try the "simple" sample like I did, just to rule out an environment issue?

**Comment by holyjak** [comment]
Hi! I am sorry, I discovered a much simpler solution to my problem, simply using a Gradle task to copy all libs into a dir, adding the spring-boot-loader.jar and the original app-only jar and using the standard `org.springframework.boot.loader.JarLauncher`. I need no fancy download-on-first-use functionality.
