### ISSUE TITLE
Gradle 6.6 not generating correct manifest: missing the value of attribute (Start-Class)

### ISSUE THREAD

**Issue by PhoenixRe32** [spring-projects-experimental/spring-boot-thin-launcher#149]
I am using the 6.6-all gradle distribution (https://services.gradle.org/distributions/gradle-6.6-all.zip)
I am using IntelliJ IDEA 2020.2
I have a very simple spring-boot app. No sub modules
The build.gradle looks like this

```
plugins {
    id "java"
    id "maven"
    id "org.springframework.boot" version "2.3.3.RELEASE"
    id "io.spring.dependency-management" version "1.0.10.RELEASE"
    id "org.springframework.boot.experimental.thin-launcher" version "1.0.24.RELEASE"
    id "io.freefair.lombok" version "5.1.0"
}

repositories {
    mavenCentral()
}

dependencies {
    developmentOnly "org.springframework.boot:spring-boot-devtools"

    implementation "org.springframework.boot:spring-boot-starter-web"
    implementation "org.springframework.boot:spring-boot-starter-validation"

    implementation "org.springframework.boot:spring-boot-starter-data-jpa"
    runtimeOnly "org.postgresql:postgresql"
    runtimeOnly "com.h2database:h2"

    implementation "guru.springframework:chuck-norris-for-actuator:0.0.2"

    testImplementation("org.springframework.boot:spring-boot-starter-test") {
        exclude group: "org.junit.vintage", module: "junit-vintage-engine"
    }
}

test {
    useJUnitPlatform()
}

group = "com.pittacode"
version = "0.1"
sourceCompatibility = JavaVersion.VERSION_11
targetCompatibility = JavaVersion.VERSION_11

springBoot {
    mainClassName = "com.pittacode.contapp.ContappApplication"
}

```

I get the error `The value of a manifest attribute must not be null (Key=Start-Class)` if I run `thinJar`
If I add 
```
botJar {
    manifest {
        attributes "Start-Class": "com.pittacode.contapp.ContappApplication"
    }
}
```
I get the same error.
If I use instead
```
jar {
    manifest {
        attributes "Start-Class": "com.pittacode.contapp.ContappApplication"
    }
}
```
I don't get an error but the jar built has a malformed manifest (no start or main class).
So If I try to run the jar (java -jar build/libs/contapp-0.1.jar I get no main manifest attribute, in build/libs/contapp-0.1.jar
Also I noticed that the jar task is skipped and bootJar is not in the chain of tasks executed

**Comment by Arrem** [comment]
After upgrading from Gradle 5.6.4 to Gradle 6.6.1 I noticed the same issue in my project. A pipeline that previously successfully built a project produced a build where the Manifest just contains a single line with the version.
```
Manifest-Version: 1.0
```

Reverting back to 5.6.4 solved the issue for me, so I assume this has something to do with one of the recent Gradle updates. A fix would certainly be appreciated!

**Comment by dsyer** [comment]
That's a pain. Help needed. FWIW it works with the "simple" sample (Gradle 6.0).

**Comment by mnewquis** [comment]
I just submitted a pull request #163  that will fix this issue.

**Comment by mnewquis** [comment]
I just submitted a pull request #164 for this.
