### ISSUE TITLE
Deployment error when parent pom is not available

### ISSUE THREAD

**Issue by oshaban** [spring-projects-experimental/spring-boot-thin-launcher#151]
When I deploy my application to Heroku via git, Maven is unable to find the artifact for my parent POM:

```
Caused by: hidden.org.apache.maven.project.ProjectBuildingException: 1 problem was encountered while building the effective model for com.company:api:0.0.1-SNAPSHOT
Sept 16 11:59:22 api app/web.2 [FATAL] Non-resolvable parent POM for com.company:api:0.0.1-SNAPSHOT: Could not find artifact com.company:parent:pom:0.0.1-SNAPSHOT in local (file:///app/.m2/repository) @ line 6, column 13
```

I have renamed the respective package names above for brevity.

Additionally, I have followed the multi pom structure example you laid out at: https://github.com/spring-projects-experimental/spring-boot-thin-launcher/tree/master/samples/multi

Running the api jar locally works fine: `java -jar api-0.0.1-SNAPSHOT.jar`

**Comment by dsyer** [comment]
How did you deploy your app? Did you ship the dependencies? Or are you expecting Heroku to be able to download them all? If so then you obviously need to deploy the parent pom as well?

**Comment by dsyer** [comment]
I think this is the expected behaviour. Please shout if you think it's something else.
