### ISSUE TITLE
java.lang.ClassNotFoundException with local jars

### ISSUE THREAD

**Issue by Madina-S** [spring-projects-experimental/spring-boot-thin-launcher#155]
I need to use local jars in the project, all of them are located in libs folder. I tried to copy the folder and its content to diffenet folder in target folder. But it is without luck. Where the local jars should be located or

**Comment by dsyer** [comment]
Local jars have to be deployed to the local Maven repository. There are other issues discussing possible enhancements (e.g. #78).
