### ISSUE TITLE
Gradle 7 support

### ISSUE THREAD

**Issue by VitaliyKulikov** [spring-projects-experimental/spring-boot-thin-launcher#166]
* What went wrong:
A problem was found with the configuration of task ':thinPom' (type 'PomTask').
  - Type 'PomTask' field 'output' without corresponding getter has been annotated with @OutputFile.
    
    Reason: Annotations on fields are only used if there's a corresponding getter for the field.
    
    Possible solutions:
      1. Add a getter for field 'output'.
      2. Remove the annotations on 'output'.
    
    Please refer to https://docs.gradle.org/7.0/userguide/validation_problems.html#ignored_annotations_on_field for more details about this problem.

**Comment by dsyer** [comment]
Did you try it and it worked?
