### ISSUE TITLE
1.0.27.RELEASE not in Maven Central

### ISSUE THREAD

**Issue by kclaes** [spring-projects-experimental/spring-boot-thin-launcher#167]
The README.md mentions `1.0.27.RELEASE` to be the latest release in Maven Central.

Meanwhile, Spring Boot `2.5.0` was released and [this](https://github.com/spring-projects-experimental/spring-boot-thin-launcher/issues/162) issue leads me to believe `1.0.27.RELEASE` is supposed to be compatible.

**Comment by jesse996** [comment]
same

**Comment by beldon** [comment]
same

**Comment by dineralex** [comment]
same

**Comment by dsyer** [comment]
1.0.27 is in Maven Central (so it 1.0.26). I don't know how to publish to Gradle Plugin Repo now that Bintray is readonly. If anyone knows, please help.

**Comment by dineralex** [comment]
@dsyer 
I don't see it in maven central. Spring 2.5.0 fails for 1.0.27.RELEASE dependency.

**Comment by dsyer** [comment]
It’s still syncing. It’s a bit slow today.

**Comment by Alceatraz** [comment]
> 1.0.27 is in Maven Central (so it 1.0.26). I don't know how to publish to Gradle Plugin Repo now that Bintray is readonly. If anyone knows, please help.

No idea, At that moment , Its not showing in mvnrepo
![not in there](https://user-images.githubusercontent.com/8266702/120877226-f7c60880-c5e7-11eb-933c-be136edfa337.png)
