### ISSUE TITLE
include/exclude of libs, like hybrid mode

### ISSUE THREAD

**Issue by cwt9562** [spring-projects-experimental/spring-boot-thin-launcher#171]
in this tool, all libs will be out of thin jar.
but my project has two module, and ont depend on another.
like multi of samples, application depend on library.
and I expect that library.jar build in application's thin jar.
like the normal spring boot jar, under `BOOT-INF/lib` dir.
and other dependencies are under `thin.root/repository` dir, out of thin jar.

i has seen #15 , but there are diff
its lib is a external jar
my lib is one of my project

**Comment by Kylin824** [comment]
meet the same question

**Comment by xiaoyunwu** [comment]
I have the same question here.
