### ISSUE TITLE
Gradle 7.2: A problem was found with the configuration of task ':thinPom' (type 'PomTask').

### ISSUE THREAD

**Issue by abn-dev-01** [spring-projects-experimental/spring-boot-thin-launcher#174]
A problem was found with the configuration of task ':thinPom' (type 'PomTask').
  - In plugin 'org.springframework.boot.experimental.thin-launcher' type 'org.springframework.boot.experimental.gradle.PomTask' field 'output' without corresponding getter has been annotated with @OutputFile.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

**Comment by dsyer** [comment]
Fixed in #178
