### ISSUE TITLE
spring-boot-maven-plugin:2.6.0 causing errors with version 1.0.27.RELEASE

### ISSUE THREAD

**Issue by duststar76** [spring-projects-experimental/spring-boot-thin-launcher#177]
Today I tried to upgrade my project to spring-boot 2.6 and run into a problem with building my project:

[ERROR] Failed to execute goal org.springframework.boot:spring-boot-maven-plugin:2.6.0:repackage (repackage) on project portal: Execution repackage of goal org.springframework.boot:spring-boot-maven-plugin:2.6.0:repackage failed: An API incompatibility was encountered while executing org.springframework.boot:spring-boot-maven-plugin:2.6.0:repackage: java.lang.AbstractMethodError: Receiver class org.springframework.boot.loader.thin.ThinLayout does not define or inherit an implementation of the resolved method 'abstract java.lang.String getLibraryLocation(java.lang.String, org.springframework.boot.loader.tools.LibraryScope)' of interface org.springframework.boot.loader.tools.Layout.

Plugin Configuration:
 ```
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
				<dependencies>
					<dependency>
						<groupId>org.springframework.boot.experimental</groupId>
						<artifactId>spring-boot-thin-layout</artifactId>
						<version>1.0.27.RELEASE</version>
					</dependency>
				</dependencies>
				<executions>
					<execution>
						<phase>install</phase>
						<goals>
							<goal>repackage</goal>
						</goals>
						<configuration>
							<excludeGroupIds>com.primingcloud</excludeGroupIds>
							<attach>false</attach>
						</configuration>
					</execution>
					<execution>
						<id>buildInfo</id>
						<goals>
							<goal>build-info</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
```

I checked  org.springframework.boot.loader.thin.ThinLayout class here on github and it looks like the getLibraryLocation is implemented.

**Comment by dsyer** [comment]
I think it was fixed in 1.0.28. I just built the Petclinic from main and it worked.
