### ISSUE TITLE
sample need update. 

### ISSUE THREAD

**Issue by xiaoyunwu** [spring-projects-experimental/spring-boot-thin-launcher#188]
these sample are very old and not useful any more due to gradle/spring update. Can some one get these updated so that it can be followed?

**Comment by dsyer** [comment]
The intention was to support a range of versions of gradle and spring. Which one were you interested in?

**Comment by dsyer** [comment]
I updated the tiny examples in the README to Spring Boot 3.0. Hopefully that makes it obvious.
