### ISSUE TITLE
Gradle build failing with gradle-8.1, same is wrking with 7.6.1

### ISSUE THREAD

**Issue by surajtambe** [spring-projects-experimental/spring-boot-thin-launcher#194]
Working Directory: C:\Users\username\git\usernameapps
Gradle user home: D:\Gradle\gradle-8.1
Gradle Distribution: Local installation at D:\Gradle\gradle-8.1
Gradle Version: 8.1
Java Home: C:\Program Files\Java\jdk-20
JVM Arguments: None
Program Arguments: None
Build Scans Enabled: false
Offline Mode Enabled: false
Gradle Tasks: build

> Task :compileJava UP-TO-DATE
> Task :processResources UP-TO-DATE
> Task :classes UP-TO-DATE
> Task :resolveMainClassName UP-TO-DATE
> Task :thinPom FAILED

FAILURE: Build failed with an exception.

* What went wrong:
A problem was found with the configuration of task ':thinPom' (type 'PomTask').
  - Gradle detected a problem with the following location: 'C:\Users\username\git\usernameapps\build\resources\main'.
    
    Reason: Task ':resolveMainClassName' uses this output of task ':thinPom' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed.
    
    Possible solutions:
      1. Declare task ':thinPom' as an input of ':resolveMainClassName'.
      2. Declare an explicit dependency on ':thinPom' from ':resolveMainClassName' using Task#dependsOn.
      3. Declare an explicit dependency on ':thinPom' from ':resolveMainClassName' using Task#mustRunAfter.
    
    Please refer to https://docs.gradle.org/8.1/userguide/validation_problems.html#implicit_dependency for more details about this problem.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
4 actionable tasks: 1 executed, 3 up-to-date

**Comment by surajtambe** [comment]
Addding following in build.gradle works but then fails on startup

thinPom.dependsOn resolveMainClassName
bootStartScripts.dependsOn thinJar
compileTestJava.dependsOn thinPom

Startup logs
Exception in thread "main" java.lang.IllegalStateException: Cannot locate launcher: C:\Users\username/.m2/repository/org/springframework/boot/experimental/spring-boot-thin-launcher/1.0.29.RELEASE/spring-boot-thin-launcher-1.0.29.RELEASE-exec.jar
        at org.springframework.boot.loader.wrapper.ThinJarWrapper.launch(ThinJarWrapper.java:131)
        at org.springframework.boot.loader.wrapper.ThinJarWrapper.main(ThinJarWrapper.java:107)

**Comment by surajtambe** [comment]
thinPom.dependsOn resolveMainClassName
bootStartScripts.dependsOn thinJar
compileTestJava.dependsOn thinPom

springBoot {
    mainClassName = 'com.sngeo.apps.SngeoApplication'
}

adding above in build.gradle works with id 'org.springframework.boot.experimental.thin-launcher' version '1.0.28.RELEASE'

**Comment by dsyer** [comment]
The Gradle problem should be fixed in 1.0.31 (works up to Gradle 8.2.1 at least).
