### ISSUE TITLE
Project does not build

### ISSUE THREAD

**Issue by werner77** [spring-projects-experimental/spring-boot-thin-launcher#205]
I tried to fork and build the project but there are multiple issues:

- mvn compile does not work due to incorrect project structuring:

```
Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:3.1.1:copy (include-layout-jar) on project spring-boot-thin-layout: Artifact has not been packaged yet. When used on reactor artifact, copy should be executed after packaging: see MDEP-187. -> [Help 1]
```

- mvn package does not work because the gradle plugin cannot be built:

```
[ERROR] Failed to execute goal on project spring-boot-thin-gradle-plugin: Could not resolve dependencies for project org.springframework.boot.experimental:spring-boot-thin-gradle-plugin:jar:1.0.32.BUILD-SNAPSHOT: Failed to collect dependencies at org.gradle:gradle-platform-jvm:jar:2.9: Failed to read artifact descriptor for org.gradle:gradle-platform-jvm:jar:2.9: The following artifacts could not be resolved: org.gradle:gradle-platform-jvm:pom:2.9 (absent): Could not transfer artifact org.gradle:gradle-platform-jvm:pom:2.9 from/to spring-libs-releases (https://repo.spring.io/release): status code: 401, reason phrase:  (401) -> [Help 1]
```

This artifact does not seem to exist in any other maven repo as well. It is also a very old version of Gradle?

**Comment by dsyer** [comment]
I can build the project, and the CI builds are green, so maybe there is something you can do - could be to do with your network environment and proxy set up? The error you pasted is a red herring I think - it just tells you where the artifact is *not*. The old version of Gradle is intentional, but I have no objection to changing it if there is a better way that still uses Maven to build it.

**Comment by dsyer** [comment]
I think the old versions of those jars were removed from a public repository. I don't know who or why, but all the builds that worked for me must have had a cached repository. I updated the "main" branch though to a newer version and it seems to work now. Give it a try.
