### ISSUE TITLE
Webapp files in src/main/webapp not in final JAR (specifically JSPs)

### ISSUE THREAD

**Issue by lukasbradley** [spring-projects-experimental/spring-boot-thin-launcher#96]
I absolutely love this project.  Well done.

However, when I've attempted to deploy a thin Jar that contains JSPs, I noticed that the webapp directory is being ignored.  I also have resources/static files that are being added to the JAR correctly, and found at runtime.  However, if I attempt to place the JSPs there, they are not found.

Any ideas?  Is it possible to include a directory in the JAR at build time?

Thanks

**Comment by dsyer** [comment]
I don't think this even works in a regular Spring Boot app (https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-jsp-limitations). There's no such thing as a thin war.
