### ISSUE TITLE
Repository declarations ignored if using thin.properties with computed=true

### ISSUE THREAD

**Issue by yimik** [spring-projects-experimental/spring-boot-thin-launcher#97]
Ignore my broken English
I like this plugin,help me a lot.

When I run with -Dthin.location=/app/，the launcher scan /app/thin.properties, and the launcher will only download artifacts from spring-snapshots (https://repo.spring.io/libs-snapshot).
I got exception like this image
![image](https://user-images.githubusercontent.com/7576454/51516480-96f06800-1e52-11e9-9c8b-7231c7893fed.png)
But my artifacts are in a private repository,and repository defined in pom.xml

**Comment by dsyer** [comment]
Does it work if you define the repository in your settings.xml? Does it work if you put the pom.xml in the thin.location? Where is the pom.xml when it isn’t working?

**Comment by yimik** [comment]
> Does it work if you define the repository in your settings.xml? Does it work if you put the pom.xml in the thin.location? Where is the pom.xml when it isn’t working?

pom.xml is in the jar file when it isn’t working.Should pom.xml be in the thin.location? I will try,thanks

**Comment by yimik** [comment]
I have tried，throw same exception.
Is there a problem with my run command?
`java -Dthin.location=file:/app -Dthin.trace=true -Dthin.debug=true -Dthin.root=/app -jar /app/app.jar`
My directory structure is as follows
```
app/
  |--repository/
  |--pom.xml
  |--thin.properties
  |--app.jar
root/
  |--.m2/
    |--settings.xml
```

**Comment by dsyer** [comment]
Is `root/` your `$HOME` (are you running in a container, maybe)? Does it actually declare the repositories you need? What about if you put the `pom.xml` in the current directory, not the `thin.location`?

**Comment by yimik** [comment]
> Is `root/` your `$HOME` (are you running in a container, maybe)? Does it actually declare the repositories you need? What about if you put the `pom.xml` in the current directory, not the `thin.location`?

Yes,run in docker,and I have declared the repositories in `settings.xml`.
I just analyzed the source code，when run with thin.properties,`computed` property will be true,the method`DependencyResolver.mavenRepositories(MavenSettings settings,DefaultRepositorySystemSession session,
List<ArtifactRepository> repositories)` will not be execute,and the repositories I declare will not use.
Is my analysis right?

**Comment by yimik** [comment]
Not really need `thin.properties`,but it's really slow when I run multiple modules at the same time,like this image
![image](https://user-images.githubusercontent.com/7576454/51526174-bdbb9800-1e6c-11e9-981a-c69b9934e720.png)
but there is no problem running single module,I think add `thin.properties` can speed up,so I try to use it and got exception

**Comment by dsyer** [comment]
For sure `thin.properties` (with `computed=true`) will improve startup time of an app. If you build your container with the dependencies cached as well (e.g. run with `thin.dryrun`) you won't need the repository declarations though, and it will be even faster.
